### ISSUE TITLE
Update to RimWorld version 1.1, permission

### ISSUE THREAD

**Issue by SaucyPigeon** [RangelReale/RR_PawnBadge#1]
I would like to try updating this mod to RimWorld version 1.1, but due to not having a license it is copyrighted. Is it possible to gain the mod author's permission to modify and distribute this mod? I understand if it is not the case. Thank you.

**Comment by RangelReale** [comment]
You can fix and submit a pull request, and I'll update it on the workshop.

**Comment by SaucyPigeon** [comment]
That's good to hear, thanks.

**Comment by SaucyPigeon** [comment]
Hi, I have added some changes to the pull request that address the ReflectionTypeLoadException issue and also include some new features. I hope you get the chance to review these changes, thanks.

**Comment by LeninsCat** [comment]
I have tested the changes that had been made by SaucyPigeon and it is completely functional with no errors with one exception being the mod manager Manifest.xml file.
`<dependencies><li>HugsLib &gt;= 6.0</li></dependencies>`
Should be 
`<dependencies><li>HugsLib &gt;= 1.2.0.0</li></dependencies>`

**Comment by RangelReale** [comment]
@SaucyPigeon well it looks like it isn't so easy do just upload these changes, and I am not with too much time to deal with this, so if you want you can upload your version with your account, and I'll put a link on my workshop page pointing to yours.

**Comment by SaucyPigeon** [comment]
Sounds good. I'll upload an updated version and post a link to it here.

**Comment by SaucyPigeon** [comment]
Here's the updated version: https://steamcommunity.com/sharedfiles/filedetails/?id=2112663412

**Comment by RangelReale** [comment]
I updated the mod page to point to your mod. Thanks!
